### ISSUE TITLE
[bikeshed] Abbreviated associated type names on Service trait

### ISSUE THREAD

**Issue by jwilm** [tokio-rs/tokio-proto#1]
Hey @carllerche! I'm super excited to try out tokio later; it looks really well done.

Just a thought as I was reading the initial announcement - I noticed the associated type names on `Service` are all shortened. Do you feel strongly about keeping the names like that? Naturally I can't speak for anyone other than myself, but I find readability goes down when reading something like `Self::Fut` vs `Self::Future`. The latter seems more descriptive and potentially more friendly.

I propose using the full names for the associated types. Also, the shed should be blue.

```rust
pub trait Service: Send + 'static {

    /// Requests handled by the service.
    type Req: Send + 'static;

    /// Responses given by the service.
    type Resp: Send + 'static;

    /// Errors produced by the service.
    type Error: Send + 'static;

    /// The future response value.
    type Fut: Future<Item = Self::Resp, Error = Self::Error>;

    /// Process the request and return the response asynchronously.
    fn call(&self, req: Self::Req) -> Self::Fut;
}
```

**Comment by Keats** [comment]
I have done the change on my fork (https://github.com/Keats/tokio/commit/f00910a2778b25fad627a4c7790f4fce260b7298).
I can do a PR if that's accepted

**Comment by carllerche** [comment]
I don't have enough of an opinion right now. Let me try to get some others to provide feedback.

**Comment by BurntSushi** [comment]
One possible point in favor of abbreviated names is that you might end of specifying the types in `where` signatures. For example: https://github.com/tokio-rs/tokio-line/blob/master/src/lib.rs#L44

**Comment by jwilm** [comment]
> specifying the types in `where` clauses

Here's the snippet from the link

```rust
pub fn serve<T>(self, new_service: T) -> io::Result<()>
    where T: NewService<Req = String, Resp = String, Error = io::Error> + Send + 'static,
{
```

This is a good argument for the abbreviated names; there's not a particularly nice way to wrap a list of associated types. Here's one attempt:

```rust
pub fn serve<T>(self, new_service: T) -> io::Result<()>
    where T: NewService<Req = String,
                        Resp = String,
                        Error = io::Error> + Send + 'static,
```

The additional bounds could also be put on a separate line which may be preferrable for some people.

```rust
pub fn serve<T>(self, new_service: T) -> io::Result<()>
    where T: NewService<Req = String, Resp = String, Error = io::Error>
          T: Send + 'static,
```

At the end of the day, the associated type names in total would be Req**uest** (4) + Resp**onse** (4) for a total of 8 extra characters. Here's the previous example with long type names:

```rust
pub fn serve<T>(self, new_service: T) -> io::Result<()>
    where T: NewService<Request = String, Response = String, Error = io::Error>
          T: Send + 'static,
```

This post just explored how an API might look with abbreviated/long and different wrapping styles. No real argument is made; I just wanted to explore and share some thoughts.

**Comment by aturon** [comment]
I'm all for expanded names here. Maybe `Reply` instead of `Response` to keep things concise?

I know there was also some question about whether to force the `Error` type to satisfy `std::error::Error`. I think that's a good idea -- I know some existing Rust web frameworks do something similar, and it's made composing middleware much nicer.

**Comment by kbacha** [comment]
My two cents:
Library types should likely be fully specified and not abbreviated. If consumers of the library think it's too verbose, allow them to type alias in their own code bases.

**Comment by posix4e** [comment]
I hate to go one way or another. Perhaps someone could propose a patch and we can see how it reads?

**Comment by Keats** [comment]
> I hate to go one way or another. Perhaps someone could propose a patch and we can see how it reads?

Something like https://github.com/Keats/tokio/commit/f00910a2778b25fad627a4c7790f4fce260b7298 or more examples?

**Comment by carllerche** [comment]
What are the thoughts about renaming `Resp` -> `Reply`?

**Comment by jwilm** [comment]
I prefer `Response` to `Reply` since it's kind of the de-facto standard name for the result of a request to a service.

**Comment by carllerche** [comment]
Alright! We switched to expanding to the full words (also `Service` is now in `tokio_service`)
