### ISSUE TITLE
Getting peer TCP address

### ISSUE THREAD

**Issue by hanscj1** [tokio-rs/tokio-proto#108]
I'm not sure if this is the correct place but I'm trying to find or figure out how to obtain the peer (remote) address of a client connecting to server that is using TcpServer for pipeline streaming? Specifically, can you obtain that info from within the Service::call(...) method or where? Thanks in advance!

**Comment by sinkuu** [comment]
You can obtain remote address at `ServerProto::bind_transport` and pass it as a part of request message so that your `Service::call` is called with the address.
https://github.com/sinkuu/tokio-framecodecs/blob/master/src/remote_addr.rs

**Comment by hanscj1** [comment]
I'll take a look. Thanks
