### ISSUE TITLE
Why tokio-proto use tokio-service as dependency?

### ISSUE THREAD

**Issue by TheWaWaR** [tokio-rs/tokio-proto#111]
As I understand `tokio_service::NewService` is a RPC call trait, because of this (the only call method):
``` rust
pub trait Service {
    type Request;
    type Response;
    type Error;
    type Future: Future<Item=Self::Response, Error=Self::Error>;
    fn call(&mut self, req: Self::Request) -> Self::Future;
}
```

In `tokio_proto::TcpServer` we see this:
``` rust
fn serve<S>(&self, new_service: S) 
    where S: NewService<Request=P::ServiceRequest, Response=P::ServiceResponse, Error=P::ServiceError> + Send + Sync + 'static
```

Is that assuming all tcp protocols are RPC protocols?

**Comment by aajtodd** [comment]
`Service` is agnostic to the underlying transport implementation and not necessarily just RPC. `call` is invoked when the underlying transport has pulled a `Request` off the wire. You get to determine what makes up a `Request`. `Service` can return a streaming `Response` as well. 

It would help to know what you are trying to do. If you want to work at a lower level though take a look at tokio-core.

**Comment by carllerche** [comment]
So, tokio-proto as a name may be a bit confusing. Tokio's *entire* purpose is to bridge a transport of frames -> Service. Which means it is entirely geared towards request / response oriented protocols.

It can handle request / response oriented protocols that have a streaming component (body), which can still make sense for pub sub like protocols. However, entirely stream oriented protocols should operate at the tokio-core layer.

Some more info [here](https://tokio.rs/docs/going-deeper/transports/)
