### ISSUE TITLE
[bikeshed] Expand Proto to Protocol

### ISSUE THREAD

**Issue by shepmaster** [tokio-rs/tokio-proto#116]
While reading through the excellent documentation, I find myself suffering some dissonance: the prose spells out the word `protocol`, but the types say `Proto`. I'm certain that that word might be typed a lot in this crate 😇 , but I've a feeling it will be read even more by consumers. I'd suggest expanding it out. 

It's also possible, but probably unlikely, that `Proto` might be conflated with `Prototype`.

As an alternative, you could also remove the pseudo namespacing entirely and go wholesale to just `tokio_proto::pipeline::Server`, since the crate is about protocols. Consumers could then opt to rename on import (`use tokio_proto::pipeline::Server as ServerProtocol`) or use it in a qualified manner, putting the namespace back on (`tokio_proto::Server::new()`).

Thank you for the exciting library!

See related #1

**Comment by dwrensha** [comment]
> As an alternative, you could also remove the pseudo namespacing entirely and go wholesale to just `tokio_proto::pipeline::Server`, since the crate is about protocols.

I'm generally a fan of this approach, though I'm yet familiar enough with this crate to say how appropriate it would be here.

I did notice that the [crate-level documentation](https://github.com/tokio-rs/tokio-proto/blob/d53f6c77b493398466852e240ae03d5dbe5684c2/src/lib.rs#L12-L15) uses this naming scheme (inconsistent with the actual code).

**Comment by carllerche** [comment]
Thanks for the report. I personally don't have a huge preference, but I don't think it is worth the breaking change at this point.

I'm going to close the issue for now, but if others disagree w/ me, it can be re-opened.
