### ISSUE TITLE
[docs] Getting Started example could use an explanation of frames

### ISSUE THREAD

**Issue by nicholasbishop** [tokio-rs/tokio-proto#123]
In the first example in the docs, https://tokio.rs/docs/getting-started/simple-server, there are a number of references to a "frame" in the code blocks, but that concept isn't defined or further explained in the text.

Specifically there are comments in the first big code block:

    // remove the serialized frame from the buffer.

and

    // Turn this data into a UTF string and return it in a Frame.

**Comment by carllerche** [comment]
A PR would be great :) It should be submitted to the website repo: http://github.com/tokio-rs/tokio-website.

I'm going to close the issue due to inactivity, but if you feel strongly about it, I would suggest re-opening an issue on the website repo instead of this one.

Cheers.
