### ISSUE TITLE
Doc navigation menus push content way down on mobile

### ISSUE THREAD

**Issue by nicholasbishop** [tokio-rs/tokio-proto#124]
Every page in the getting started docs requires scrolling way down. Attached a composite screenshot of what https://tokio.rs/docs/getting-started/tokio/ looks like on my phone with Chrome:

![tokiomobilebug](https://cloud.githubusercontent.com/assets/1023208/21967220/c2f324c0-db50-11e6-997f-4001310f1a88.png)

**Comment by carllerche** [comment]
Thanks for the report. I moved this issue to the appropriate repo: https://github.com/tokio-rs/website/issues/61
