### ISSUE TITLE
Doc unclear on how to "translate" from tokio-core to tokio-proto

### ISSUE THREAD

**Issue by nicholasbishop** [tokio-rs/tokio-proto#126]
In the [Example: a toy HTTP+TLS client using core](https://tokio.rs/docs/getting-started/tls/) doc, it says:

> In this example we’ll only use tokio-core for now rather than tokio-proto, but the concepts should translate quite readily.

There's no further mention of tokio-proto on that page though, so it's not clear how to translate it to tokio-proto.

**Comment by alexcrichton** [comment]
FWIW it all boils down to an implementation of `Io`. Most [implementations of `ServerProto`](https://github.com/tokio-rs/tokio-minihttp/blob/master/src/lib.rs#L23-L32) are generic over `Io` and the `BindTransport` future allows you to do work with an I/O object before returning it, such as an SSL handshake.

Essentially the translation for TLS would look like:

* Store a `TlsAcceptor` context in your protocol object
* When `bind_transport` is called, use that to call `connect_async`
* Return that all as a future

**Comment by carllerche** [comment]
Hopefully this clears things up. If it doesn't, please open a new issue on http://github.com/tokio-rs/tokio-website (since this appears to be a website bug) and reference this one.
