### ISSUE TITLE
Doc suggestion: add a glossary

### ISSUE THREAD

**Issue by nicholasbishop** [tokio-rs/tokio-proto#127]
I think that https://tokio.rs/docs/getting-started/tokio/ would benefit from a glossary of terms covering tokio-core, tokio-proto, tokio-service, and futures. I think a lot of the terms are already explained well in isolation on various pages, but a single page that brings all the definitions together would be helpful.

**Comment by casey** [comment]
This would be great, especially something which documented all the types and their relationships, such as `Codec`, `Dispatch`, the various `Proto`s, etcetera.

**Comment by aturon** [comment]
Great idea!

**Comment by carllerche** [comment]
I moved this issue to the website repo: https://github.com/tokio-rs/website/issues/62
