### ISSUE TITLE
Ensure there's a method for "I'm done writing"

### ISSUE THREAD

**Issue by alexcrichton** [tokio-rs/tokio-proto#141]
This is a movement of https://github.com/tokio-rs/tokio-core/issues/67 with more details here: https://github.com/tokio-rs/tokio-core/issues/67#issuecomment-277568046.

We should make sure that the `Transport` traits have a method to tell the underlying object that they're done receiving frames to trigger a graceful shutdown at the protocol level, if necessary.

**Comment by wfraser** [comment]
Agreed; there are protocols out there that require one party to close the connection to signal the end.

For non-multiplexed protocols this is pretty simple, but for multiplexed protocols, it needs to not drop the connection unless there are no more requests active and/or all requests have signaled their desire to drop.

FastCGI is one example of a multiplexed, streaming protocol where the connection should be closed by the server when the last request is done, and I haven't found a way to implement this correctly with tokio-proto yet.

**Comment by carllerche** [comment]
`Sink` is getting a `close` fn, which handles this: https://github.com/alexcrichton/futures-rs/pull/404
