### ISSUE TITLE
Setting tcp_no_delay when using TcpServer API

### ISSUE THREAD

**Issue by sunng87** [tokio-rs/tokio-proto#142]
I'm using tokio-proto over tokio-core. And I realized that in tokio-core, there is APIs to configure TCP options on the socket struct. However, it seems the socket is inaccessible when we use tokio-proto APIs like `TcpServer::new(...).serve(|| ...)`.

Options like no_delay are very important to our server performance. So I hope we can have a route to configure these things while keeping the API elegance brought by tokio-proto.

**Comment by carllerche** [comment]
Hey, thanks for the report. I think that the TCP builders definitely should have options to configure the TCP socket built in. However, until we add them, you configure them yourself by handling it in the `ServerProto` impl, specifically, something like:

```rust
impl ClientProto<TcpClient> for LineProto {
    type Request = String;
    type Response = String;

    type Transport = Framed<TcpClient, LineCodec>;
    type BindTransport = Result<Self::Transport, io::Error>;

    fn bind_transport(&self, io: TcpClient) -> Self::BindTransport {
        // Configure TCP socket options here.
        Ok(io.framed(LineCodec))
    }
}
```

**Comment by sunng87** [comment]
@carllerche Thank you! That's really helpful!

And to be clear, I think it's `tokio_core::net::TcpStream` for `ClientProto<TcpStream>`.

It works great for me and I think it's OK to close this.
