### ISSUE TITLE
Multiplexing: RequestId type is fixed to u64

### ISSUE THREAD

**Issue by koivunej** [tokio-rs/tokio-proto#147]
Currently `RequestId` type is fixed as `u64` and is generated at client. I propose that multiplexing should be generic over some `trait RequestId: Hash + Eq + Debug + Copy {}` and this of course would mean that `RequestId` generation has to happen somehow other than by keeping a counter.

My use case is a multiplexed protocol where identifiers are `Uuid`s.

If this feature is not of any importance to the project at the moment, any mentorship or advice would be appreciated.

**Comment by aajtodd** [comment]
See #129

**Comment by koivunej** [comment]
Thanks @aajtodd, missed #129. Closing as duplicate.
