### ISSUE TITLE
Error handling issue

### ISSUE THREAD

**Issue by ari7** [tokio-rs/tokio-proto#165]
`Err()` produced by server service or server-side `codec::encode` causes client connection to hang. If I understand correctly, when protocol doesn't support encoding error frames, `Err()` produced by `Encoder::encode` must terminate the connection. Currently, what happens is, the client-side service call will remain unresolved.

I've slightly modified the following examples from [tokio-line](https://github.com/tokio-rs/tokio-line) to demonstrate the issue:

- `streaming/examples/stdout_server.rs`
- `simple/examples/echo_client_server.rs`

Available here: https://github.com/ari7/tokio-line

**Comment by ari7** [comment]
Ok, I think I got a bit closer to finding the cause of this issue.

I've split the `streaming/stdout_server` into server and client apps. I started the server and connected to it using `telnet` first.  Server would drop the connection correctly (on `Err`). When I tried to connect w/ the client, it would hang. I have inspected the server log (via `RUST_LOG=trace`) and it was the same (whether I connect from telnet or from example client). ([Tail of the log](https://gist.github.com/ari7/81267a08a2ae9544995f97aa9c847fe5))

So, it looks like the source of this issue is on the client side. In the following snippet (copied from the `streaming/stdout_server` example), when server drops the connection (after service or codec return `Err`), the `client.call` future doesn't resolve to anything:

```Rust
fn client(addr: &str) {
    let addr = addr.parse().unwrap();

    let mut core = Core::new().unwrap();
    let handle = core.handle();

    core.run(
        Client::connect(&addr, &handle)
            .and_then(|client| {
                client.call(Line::Once("Hello".to_string()))
                    .then(|res| {
                        println!("CLIENT: result: {:?}", res);

                        Ok(())
                    })
            })
    ).unwrap();
}
```

**Comment by ari7** [comment]
The client-side end of communication doesn't properly handle the situation when server unexpectedly drops the connection. This is the place in code that could be causing this: ([src/streaming/pipeline/advanced.rs](https://github.com/tokio-rs/tokio-proto/blob/master/src/streaming/pipeline/advanced.rs#L258-L262)):

```rust
fn write_in_frames(&mut self) -> io::Result<()> {
    // Write the next in-flight in message
    match try!(self.dispatch.get_mut().inner.poll()) {
        // ...
        Async::Ready(None) => {
            trace!("   --> got None");
            // The service is done with the connection.
            break;
        }
        // ...
    }

    Ok(())
}
```

Client-side log: https://gist.github.com/ari7/549bcd687002d3dea7595e0d382639e5.

Server dropping connection is simply ignored and the future continues to be polled. 
@alexcrichton

**Comment by alexcrichton** [comment]
cc @carllerche does this sound familiar?

**Comment by ari7** [comment]
Another thing to note: when server flushes an empty transport, client detects this as "client dropped", which looks to me incorrect.

I've added [an example crate](https://github.com/ari7/tokio-line/tree/master/streaming/examples/error_handling_debug) to [my tokio-line fork](https://github.com/ari7/tokio-line) for tracking this bug. It accepts either `--server` or `--client` flag to start either of the sides.

**Comment by carllerche** [comment]
Sorry about the delay responding to this issue.

As a result of the discussion in the Tokio RFC, the streaming aspect of tokio-proto are going to be deprecated. As such, I don't think this bug is going to get fixed. I would recommend moving away from tokio-proto for your streaming protocol needs.
