### ISSUE TITLE
Example for upload/download progress

### ISSUE THREAD

**Issue by kpcyrd** [tokio-rs/tokio-proto#185]
hey, was wondering if it's useful (or already possible) to access the write progress when sending a Request/Response. Assuming the following code (with `data` holding a lot of data):
```rust
info!("(upload) send: {:?}", data);
let url = core.run(client.call(data.into()));
info!("(upload) got: {:?}", url);
```
I would like to be able to print a progress bar. I think tokio is aware (internally) how much of the data has been successfully sent, and also knows how large the request is (the difference of bytes before and after calling `MyCodec::encode` with my request).

I understand this is probably a large change/too large of a change, hopefully this might be interesting input for the revamp in the later case. :)

**Comment by carllerche** [comment]
Thanks for the report.

As a result of the Tokio RFC, tokio-proto is going to be significantly simplified. As such, this kind of feature will be out of scope.
