### ISSUE TITLE
Using a timer in a transport is a CPU hog

### ISSUE THREAD

**Issue by SirVer** [tokio-rs/tokio-proto#19]
I implemented the PingPongTransport that we discussed in IRC the other day. I was fairly successful getting it to work, but unfortunately it is a huge CPU hog.

Repro case is in a [branch of my fork of tokio-line](https://github.com/SirVer/tokio-line/tree/timeout), based on master: https://github.com/SirVer/tokio-line/commit/add57a8888a377a3b15ce68c9183a959d0fad4a4. 

This is what I see: running `cargo run --example echo` gives me a process that takes 0 CPU. Now calling netcat using `nc localhost 12345` and letting it sit there for 5 seconds (until disconnect): the server takes ~0% CPU till disconnect, then, the CPU usage rises steeply till ~40% CPU. 

If I type something once during the first 5 seconds pushes CPU usage to > 100% CPU on 5 threads. This usage never drops again, even with no open TCP connections to the server until the server is killed. Not using the PingPongTransport (just Line) does not show these problems. 

It seems like tokio is doing a lot of work on those dropped connections.

This is on Mac OS X using rust ccargo 0.13.0-nightly (5593045 2016-08-16) and rustc 1.12.0-nightly (1bf5fa326 2016-08-16).

**Comment by carllerche** [comment]
Thanks for the repro. I'll take a look at it. It definitely sounds like something is wrong.

**Comment by carllerche** [comment]
Ok, this should be fixed by using `tokio-timer` (I hope)
