### ISSUE TITLE
Server welcome message or banner

### ISSUE THREAD

**Issue by jocutajar** [tokio-rs/tokio-proto#191]
Hi,

As will be true for other protocols, in SMTP the server should display a welcome banner upon establishing connection (220 <domain> service ready) which is a signal for the client to start sending commands. This seems to be in conflict with the request-response paradigm. 

I can imagine protocols could be completely inverted such as server sending requests and client responses. But for this moment I'm only concerned with the welcome message upon connection. After that the client request => server response would be upheld.

The solution I'd propose is that the codec is called immediately after receiving connection with an empty buffer if there's no data ready or, similarly like with EOF, there would be an extra method with default implementation for that. Stateful `Decoder` can handle this as connection initialization and generate an opening frame request. Service can then produce the welcome frame response.

I keep trying to figure where to hook this in, but the `bind_server`, `bind_transport` are super cryptic to me. Do i need to implement the transport? Please help.

fyi: [my wip study project on github](https://github.com/jocutajar/ResistRustNot.SmtpServer/tree/develop)

Thanks a lot

**Comment by jocutajar** [comment]
I found the solution. It is by creating a transport decorator: https://stackoverflow.com/a/46877956/481812
It may be useful to show this in examples, otherwise the issue can be closed.
Thank you

**Comment by carllerche** [comment]
Looks like this is resolved. I am closing the issue.
