### ISSUE TITLE
message rate

### ISSUE THREAD

**Issue by yoni386** [tokio-rs/tokio-proto#197]
Hello,

Can you please share the limitations / general statistics (basic high level performance results). 
How large can be the bytes array that pass between the points? how many messages / bytes can passed (point to point)?
Bandwidth per second results? was it checked with high speed network 25Gb, 50Gb, 100Gb? 

It might be  "replacement" for MPI / rdma maybe this can fit better in rust. In my case, I don't need to register "pin" remote memory but the actual data (bytes) need to pass fast.

Thank you,

Yoni

**Comment by carllerche** [comment]
The numbers that you are looking for are going to be very specific to your use case and environment. The only way that you will get an accurate value would be to try experimenting yourself.

Sorry for the vague answer, but hope this helps :).
