### ISSUE TITLE
Allow to perform startup ops on reactor

### ISSUE THREAD

**Issue by daschl** [tokio-rs/tokio-proto#23]
As far as I can see a reactor takes over one thread and runs its tasks on it - what I'd like to be able to do is use something like [hwloc](https://github.com/daschl/hwloc-rs) to pin event loop threads to certain cores.

I was thinking maybe a hook/callback thats gets executed once the reactor has taken over? Probably doing a oneshot task after startup might also work, but I wanted to bring it up in case there is more benefit in having an explicit "configure this reactor somehow after startup" in some way or another.

**Comment by carllerche** [comment]
Good thoughts. There is a lot of in progress reactor work, so I'm going to leave this open for now as a placeholder to discuss this again when the changes land.

**Comment by carllerche** [comment]
Ok, this should be handled now by `tokio-core` and passing in a future to `run`.
