### ISSUE TITLE
Example in documentation for tokio_proto::server::listen hangs

### ISSUE THREAD

**Issue by jcsoo** [tokio-rs/tokio-proto#34]
In the documentation for [tokio_proto::server::listen](http://rust-doc.s3-website-us-east-1.amazonaws.com/tokio-proto/master/tokio_proto/server/fn.listen.html), the following code to launch the server hangs before it gets to bind, meaning that attempted connections produce "Connection Refused".

```
fn main() {
    let mut lp = Loop::new().unwrap();

    // Launch the server
    server::listen(lp.handle(),
                   "0.0.0.0:3245".parse().unwrap(),
                   |stream| Ok(Connection::new(stream)));

    // Run the reactor
    lp.run(futures::empty::<(), ()>()).unwrap();
}
```

After a suggestion to look at a [similar example](https://github.com/tokio-rs/tokio-line/blob/master/src/service.rs#L45-L55) in tokio-line, I have a modified version that appears to work:

```
fn main() {
    let mut lp = Loop::new().unwrap();    
    let loop_handle = lp.handle();

    loop_handle.clone().spawn(move |_| {
        server::listen(loop_handle,
                    "0.0.0.0:3245".parse().unwrap(),
                    |stream| Ok(Connection::new(stream)))
        .then(|r| {
            r.expect("failed to listen");
            Ok(())
        })                
    });
    
    lp.run(futures::empty::<(), ()>()).unwrap();
}
```

I think the reason the documentation example fails is because server::listen returns a future which is never actually attached to an event loop. The signature makes things a little confusing because listen takes a LoopHandle as the first parameter, which suggested to me that it might register itself somehow.

The reworked example also has a few tricky parts - the outer loop_handle must be moved into the closure, and the .then() (or maybe a .map_err()) must be used to change the error type from io::Error to ().

**Comment by carllerche** [comment]
This should be fixed by 2d6f909b5e48574fce1a0dd4fd171ba8fb558dad
