### ISSUE TITLE
Documentation link is broken in the README

### ISSUE THREAD

**Issue by vmalloc** [tokio-rs/tokio-proto#39]

**Comment by frewsxcv** [comment]
Might get fixed by https://github.com/tokio-rs/tokio-proto/pull/38

**Comment by frewsxcv** [comment]
Documentation is now being deployed: https://tokio-rs.github.io/tokio-proto/tokio_proto/index.html

**Comment by vmalloc** [comment]
Thanks!!!

**Comment by carllerche** [comment]
Thanks for the report.
