### ISSUE TITLE
Should <T as Service>::Error also impl std::error:Error

### ISSUE THREAD

**Issue by killercup** [tokio-rs/tokio-proto#4]
Just for convenience  when working with errors, it might be nice if [Service::Error](https://github.com/tokio-rs/tokio/blob/08d52de7377067e4d857cdf3504848d290f88119/src/service.rs#L139) would be `type Error: ::std::error::Error + Send + 'static;`.

**Comment by carllerche** [comment]
I believe that this is the right thing to do!

**Comment by carllerche** [comment]
There was a comment on /r/rust about how requiring `std::error::Error` would prohibit using `()` as the error type. Perhaps this question should be punted upstream to the `futures` crate?

**Comment by carllerche** [comment]
`Service` was moved to tokio-service. However, bounding `Error` by `std::error::Error` was discussed and it was decided that bounding the trait w/ `std::error::Error` would be too limiting for the primary trait.
