### ISSUE TITLE
The documentation for server::listen does not use the listen function

### ISSUE THREAD

**Issue by matt2xu** [tokio-rs/tokio-proto#41]
A small issue in the documentation for the listen function showing code that does not use it :-)

I see that the example was changed in commit 2d6f909.
I'm using server::listen in my example as follows and it seems to work as expected:

``` rust
let mut core = Core::new().unwrap();
let handle = core.handle();

let addr = "0.0.0.0:113".parse().unwrap();
server::listen(&handle, addr, move |stream: TcpStream| {
    // ...
}).unwrap();

core.run(futures::empty::<(), ()>()).unwrap();
```

Would you accept a pull request replacing the example in the documentation with something like the code above?

**Comment by euclio** [comment]
Just curious: why is the `core.run(futures::empty::<(), ()>()).unwrap();` required?

**Comment by matt2xu** [comment]
I don't remember exactly :-) I saw that in an example somewhere, and when I removed that call nothing was happening.

**Comment by matt2xu** [comment]
To be more precise, the last line core.run(...) runs a future that is never ready. It keeps the program alive, otherwise your program just ends. You can see it as a blocking wait basically.

**Comment by carllerche** [comment]
It also runs the actual event loop :) If you replaced it w/ `thread::sleep` nothing would happen as well.

**Comment by alexcrichton** [comment]
This has now been removed, so closing.
