### ISSUE TITLE
Exposing errors in Parse trait

### ISSUE THREAD

**Issue by alexcrichton** [tokio-rs/tokio-proto#51]
Right now it looks like `Parse` doesn't have the ability to expose an error from a failed-to-parse request (it just returns an `Option`). Perhaps it could be:

``` rust
 fn parse(&mut self, buf: &mut BlockBuf) -> Poll<Self::Out, io::Error>;
```

or maybe even generic over the error?

**Comment by tmiasko** [comment]
I experimented with similar idea, and having `Result` there feels like
ergonomic win given that parsing usually gives ample of opportunities for
errors of various kinds.

Additionally once `Result` is there, signalling readiness through `Async` type
seems like sensible thing to do. Though, I would be a little reluctant to limit
errors only to `io::Error`.

**Comment by cstorey** [comment]
I've had a similar issue, but I ended up working around it by encoding parse errors into the `Error` variant of [Frame](https://github.com/tokio-rs/tokio-proto/blob/a0998dcd681715d2dc59e5399c983b8bb816fa99/src/pipeline/mod.rs#L43-L57). That doesn't really seem right, so I'd love to see a solution here.

**Comment by aturon** [comment]
No longer relevant.
