### ISSUE TITLE
Default implementation of Parse::done

### ISSUE THREAD

**Issue by alexcrichton** [tokio-rs/tokio-proto#52]
Right now this looks like:

``` rust
    /// Called when there are no more inbound bytes
    fn done(&mut self, _buf: &mut BlockBuf) -> Option<Self::Out> {
        None
    }
```

Perhaps though this should call `parse` by default? If `parse` returns `NotReady` then it seems like this may also wish to return an error (didn't get a whole request as part of the last pieces of the body).

Taking the suggestion from #51 about returning an error, perhaps something like:

``` rust
    fn done(&mut self, buf: &mut BlockBuf) -> io::Result<Self::Out> {
        match try!(self.parse(buf)) {
            Async::Ready(pair) => Ok(pair),
            Async::NotReady => {
                Err(io::Error::new(io::ErrorKind::Other, "bytes left over"))
            }
        }
}
```

That is, `done` never returns `NotReady` but could fail if there's data left over.

**Comment by carllerche** [comment]
This has happened in tokio-io
