### ISSUE TITLE
Location of `try_read` traits

### ISSUE THREAD

**Issue by alexcrichton** [tokio-rs/tokio-proto#53]
Right now there's a macro in `tokio-core`, `try_nb!`, which serves a purpose similar to these. If we keep the traits they probably want to be in `tokio-core`, but if the macro suffices we may want to remove the traits?

**Comment by carllerche** [comment]
Historically when using the `try_` variants of fns when mio had it, I recall usually not wanting to return the `NotReady` immediately. Another thing to consider is you can get the same behavior as `try_nb` by doing: `try_ready!(io.try_read(...)`.

The only case of `try_read` in tokio-proto itself doesn't return on `NotReady`: https://github.com/tokio-rs/tokio-proto/blob/master/src/framing.rs#L105-L120

I think wanting to inject logging is not unusual.

**Comment by aturon** [comment]
I agree that this functionality, in whatever form we have it, should live in `tokio-core`. I propose we make a 0.2 issue there to do a final pass over the various `try_*` macros as well as these traits, and figure out a coherent overall story. (I don't have a strong opinion about it just now, I'd want to put them all together and figure out a good, simple way to get the coverage we need).

**Comment by alexcrichton** [comment]
I'm generally not a huge fan of new traits as well as they require an extra import to use (whereas another strategy might not). If we arrange for some sort of standard prelude in tokio-core then it may not be bad, but having these functions for ergonomic value I don't think pulls their weight if you *also* have to import every time you use them.

**Comment by carllerche** [comment]
This has been moved out for 0.1.
