### ISSUE TITLE
ServerService vs Service<...>

### ISSUE THREAD

**Issue by alexcrichton** [tokio-rs/tokio-proto#56]
The pipeline/multiplex modules have a separate `ServerService` trait which is a specialization of the generic `Service` trait. This does allow implementing `ServerService` and using it without implementing `Service`, but it's also cognitively another trait to keep in your head. Would it be possible to remove the `ServerService` traits in favor of just taking a `Service` with a special set of arguments?

**Comment by carllerche** [comment]
I think getting rid of `ServerService` is probably best... it's was mostly added to manage the generics, but shouldn't be exposed to the end user.

**Comment by carllerche** [comment]
ServerService is gone
