### ISSUE TITLE
doc: Frame::MessageWithBody

### ISSUE THREAD

**Issue by alexcrichton** [tokio-rs/tokio-proto#57]
Every time I see this variant I feel like I always get it backwards. For the life of me I can't actually figure out what `Sender` is connected to.

Perhaps the docs could be bolstered here with this respect? E.g. it says that body frames are proxied to the sender, but where's the receiver live?

**Comment by carllerche** [comment]
`Frame` was significantly changed since this issue. I believe it is fixed. If not, please re-open.
