### ISSUE TITLE
doc: Examples

### ISSUE THREAD

**Issue by alexcrichton** [tokio-rs/tokio-proto#58]
`tokio-proto` is quite a generic crate, but this means that as a first-timer it's often very difficult to wrap your head around all the generics and figure out what's what. Perhaps some key examples could be given for functions like `connect`, `Server::new`, etc, which show off what's happening?

One option may be to bundle the line protocol with this repository as an example, because in theory it's quite simple, right?

**Comment by alexcrichton** [comment]
Er the bundling would specifically be for just the doc examples to compile.

**Comment by carllerche** [comment]
This has been done w/ https://tokio.rs/
