### ISSUE TITLE
`server::listen` does not support reuse address and reuse port options

### ISSUE THREAD

**Issue by penberg** [tokio-rs/tokio-proto#59]
The `server::listen` function expects a socket address, which makes it impossible to configure things like `SO_REUSEADDR` and `SO_REUSEPORT` that are needed for distributing connections across multiple threads.

If the API required callers to pass a `net::TcpListener` to the function, people can use `net2::TcpBuilder` and `net2::unix::UnixTcpBuilderExt` to configure their listener.

**Comment by alexcrichton** [comment]
Note that this is the purpose of the [`TcpListener::from_listener` API](https://tokio-rs.github.io/tokio-core/tokio_core/net/struct.TcpListener.html#method.from_listener) where the defaults mirror libstd but you can configure your own listener and then use it with futures.

Also note that the implementation of this function is quite small:

```rust
    let handle2 = handle.clone();
    handle.spawn(socket.incoming().for_each(move |(socket, _)| {
        let future = new_future(socket);
        handle2.spawn(task.map_err(|e| {
            error!("task error: {}", e);
        }));
        Ok(())
    }).map_err(|e| {
        error!("server error: {}", e);
    }));
```

**Comment by penberg** [comment]
Sure, I am already using `TcpListener::from_listener` and I certainly can just duplicate that functionality.

However, the documentation for `server::listen` and friends state that they're implementing a generic TCP/IP server, which IMHO should allow the caller to _somehow_ enable reuse address and reuse port, because it's otherwise impossible to take advantage of kernel support for distributing connections across threads.

**Comment by carllerche** [comment]
`server::listen` will be going away for now in favor of doing it manually. This will enable configuring the socket as desired.
