### ISSUE TITLE
Clarify In/Out terminology

### ISSUE THREAD

**Issue by alexcrichton** [tokio-rs/tokio-proto#64]
Commented here: https://github.com/tokio-rs/tokio-proto/pull/62#discussion_r82087908

I personally interpret in/out with one of two interpretations:
- Read out a request, write in a response.
- Read in a request, write out a response.

Unfortunately these mean opposite things :(. Looks like this is standard terminology in finagle though? (cc https://github.com/tokio-rs/tokio-proto/pull/62#discussion_r82124234). Maybe I should just shift how I view these?

(may also be worth exploring alternative names)

**Comment by seanmonstar** [comment]
FWIW, in hyper I have the concept of Incoming vs Outgoing. This distinction appears in other HTTP libraries that I've looked at. This causes a very odd-looking case:

```rust
impl<T> FramedIo for Conn<T> {
    type In = T::Outgoing;
    type Out = T::Incoming;
    // ...
}
```

**Comment by carllerche** [comment]
In my terminology, In = message going into the socket, Out = "message coming out of the socket"

What is incoming / outgoing in your case?

**Comment by seanmonstar** [comment]
Incoming = message incoming to this machine, Outgoing = message going out from this machine.

**Comment by tikue** [comment]
This is confusing every time for me. I don't think inverting the in/out cases would make it any more intuitive.

**Comment by aajtodd** [comment]
Usually seen as the second choice: Read in a request, write out a response. I think it would be very confusing the other way around.

This matches Finagle Service definitions [Finagle Services](http://twitter.github.io/finagle/guide/ServicesAndFilters.html#services) as well as Wangle (and pretty much any socket library I've worked with for what it's worth). 

What I don't see or haven't wrapped my head around is the [filters](http://twitter.github.io/finagle/guide/ServicesAndFilters.html#filters) part of Framing for tokio. I know I've gone back and forth with @carllerche on this in https://github.com/tokio-rs/tokio-proto/issues/63 and gitter but embedding the types that way seems rather limiting and requires lots of boilerplate and manual plumbing.

**Comment by carllerche** [comment]
There is no more In / Out.

**Comment by tikue** [comment]
There is in `Codec`. Is it worth reopening this in tokio-core, or is it less ambiguous in that usage?

**Comment by alexcrichton** [comment]
@tikue sure yeah, I've opened one: https://github.com/tokio-rs/tokio-core/issues/135
