### ISSUE TITLE
Transport::{write, flush} should return a custom enum

### ISSUE THREAD

**Issue by kamalmarhubi** [tokio-rs/tokio-proto#7]
Currently these both return `io::Result<Option<()>>` with no explanation of what the difference between `Some(())` and `None` is meant to be.

**Comment by carllerche** [comment]
I think that it should change to `futures::Poll` but I am waiting for the resolution of alexcrichton/futures-rs#108

**Comment by carllerche** [comment]
Handled by `FramedIo` in `tokio_core`
