### ISSUE TITLE
easy/pipeline/server

### ISSUE THREAD

**Issue by hanscj1** [tokio-rs/tokio-proto#77]
It appears that FramedIo is being deprecated (according to doc) and minihttp code is not up to date with the latest of the other tokio repos. This piece of code doesn't work any longer and when changed to Framed the new method went away etc...

So, what is the best way to handle something like the easy/pipeline/server new with the update libraries? Example of minihttp code:

NOTE: Tried socket.framed(HttpCodec);  // Merged Decoder/Encoder to support Codec changes.
       // Create the transport
        let transport = EasyFramed::new(socket,
                                        request::Decoder,
                                        response::Encoder);

        // Return the pipeline server task
        let server = pipeline::EasyServer::new(service, transport);
        handle.spawn(server.map_err(|e| {
            println!("error: {}", e);
        }));

**Comment by hanscj1** [comment]
Maybe a better question. What would be the recommend way to implement an HTTPs like server similar to minihttp?

**Comment by colindjk** [comment]
So this won't exactly answer your question, but have you looked at https://github.com/popravich/minihttp? Apparently that's the new hip 'minihttp' people are talkin' about, so if you were looking at 'tokio-minihttp'... that's _so_ last month.

At this moment however 'popravich/minihttp' is not updated for tokio-core's most recent version, only tokio-proto, but based on where you asked this question, that should be oki. 

Hope this helped.

**Comment by carllerche** [comment]
Sorry, the update to this lib is lagging a bit. The PR is in progress here https://github.com/tokio-rs/tokio-proto/pull/75

**Comment by hanscj1** [comment]
Thanks for the update. So, it appears the code (similar) to minihttp will be moved here with PR for an http protocol?

**Comment by alexcrichton** [comment]
PR is merged! I'll update minihttp shortly.
