### ISSUE TITLE
Can't infer BindServer from ServerProto in doc example

### ISSUE THREAD

**Issue by mthvedt** [tokio-rs/tokio-proto#80]
The "Doubler" example server in the docs at https://tokio-rs.github.io/tokio-proto/tokio_proto/index.html does not work.

To reproduce:
* Create a new project with a main.rs, and copy-paste the example code into main.rs.
* Set up an appropriate Cargo.toml.
* Execute `cargo run`.

or clone https://github.com/mthvedt/tokio-proto-example and execute `cargo run`.

This yields the following error (on stable and nightly):
```
error[E0277]: the trait bound `IntProto: tokio_proto::BindServer<_, tokio_core::net::tcp::TcpStream>` is not satisfied
  --> src/main.rs:94:5
   |
94 |     TcpServer::new(IntProto, addr)
   |     ^^^^^^^^^^^^^^ trait `IntProto: tokio_proto::BindServer<_, tokio_core::net::tcp::TcpStream>` not satisfied
   |
   = note: required by `<tokio_proto::TcpServer<Kind, P>>::new`
```

I can reproduce this consistently on stable and nightly on two different machines (both Macs). It is not clear to me why the doc tests compile, but this example does not.

**Comment by mthvedt** [comment]
If you copy `src/main.rs` to a checkout of `tokio-proto`, `cargo run` works just fine. The breakage seems to depend on using `tokio-proto` as a dependency.

**Comment by mthvedt** [comment]
The issue was on my end: different versions of tokio-core. However, that error message is extremely opaque.

**Comment by jonhoo** [comment]
For other people hitting this issue: you need to name `tokio-core` in your `Cargo.toml` with the same version as `tokio-proto` uses. See `tokio-proto`'s [`Cargo.toml`](https://github.com/tokio-rs/tokio-proto/blob/master/Cargo.toml).

**Comment by jonhoo** [comment]
And same for `tokio-service`.
