### ISSUE TITLE
Unable to store result of TcpClient::connect()

### ISSUE THREAD

**Issue by hjr3** [tokio-rs/tokio-proto#81]
When going through TcpClient or directly calling `bind_client()`, I get a concrete type of `tokio_proto::pipeline::client::ClientService<tokio_core::net::TcpStream, _>`. However, the client module is private. How am I to store a client on some struct?

https://github.com/tokio-rs/tokio-proto/blob/master/src/tcp_client.rs#L47

Example of what I am trying to do: 

```rust
let client = TcpClient::new(backend::Backend);
client.connect(&addr, &handle.clone()).map(|client| {
    let foo = Foo::new(client);
});
```

**Comment by hjr3** [comment]
```rust
pub struct Backend;

impl<T: Io + 'static> ClientProto<T> for Backend {
    type Request = Request;
    type RequestBody = Vec<u8>;
    type Response = Response;
    type ResponseBody = Vec<u8>;
    type Error = io::Error;
    type Transport = framed::Framed<T, HttpCodec>;
    type BindTransport = io::Result<framed::Framed<T, HttpCodec>>;

    fn bind_transport(&self, io: T) -> Self::BindTransport {
        Ok(framed::framed(io, HttpCodec))
    }
}

pub struct HttpCodec;

impl Codec for HttpCodec { ... }

```

**Comment by ashleysommer** [comment]
Same problem.
Not sure, but I think ClientService should be exposed publicly in the pipeline::client module.
