### ISSUE TITLE
Futures hanging when making two concurrent requests from a client

### ISSUE THREAD

**Issue by tikue** [tokio-rs/tokio-proto#84]
I don't have a *minimal* test case, but I do have a 300-LOC [example](https://github.com/tikue/tarpc/blob/proto-changes/examples/readme_expanded.rs). This could very well be a problem in my code, but I haven't been able to identify any glaring errors, so I thought perhaps it'd be good to at least get some more eyes on it.

cc @carllerche who encouraged me to open a bug :)

**Comment by alexcrichton** [comment]
Nothing looks glaring to me as-is, but I didn't really dig in *too* deeply to the example. A smaller starting point would definitely help out quite a bit!

**Comment by tikue** [comment]
Cut it down to < 130 loc.

**Comment by tikue** [comment]
Carl helped me debug it. I was being silly and clearing the remaining buffer after decoding a message.
